### ISSUE TITLE
Plugin not working for left side menu

### ISSUE THREAD

**Issue by nileshnpathade** [iarenaza/moodle-filter_multilang2#34]
we observe that multilang filter is working in the course body, but it seems not working on left side menu for student role. It works for teacher role, but only on editing mode.
![image](https://user-images.githubusercontent.com/13468332/205332128-d87b4130-2a56-49b6-af13-74707fc8fe14.png)

**Comment by izendegi** [comment]
Hi @nileshnpathade 

Looking at your image I couldn't see what the problem is because there wasn't any {mlang} notation, but after testing I've discovered that the left index menu doesn't change when the user chooses another language.

As far as it applies correctly the filters I would say it isn't a issue of this filter but a bug on the Moodle core side; it may be a cache issue on Moodle core, but I would need more research to say that without a doubt.

**Comment by nileshnpathade** [comment]
Thank you for the comments and share your thoughts

Yes looks error but not sure about plugin or core code.

Apologize putting here. But I posted at moodle fourm too.

Could you please assist me what is issue. 
 it's lang not reflect to left side topic name and activities names.

**Comment by nileshnpathade** [comment]
If you can my screenshot on above, left side panel in English and main course page in Welsh language.
After swtiching language left panel activity name and topic name not change with selected langulage. 

IT COULD BE PROBLEM WITH MOODLE CACHES.

**Comment by izendegi** [comment]
Hi, 

Just noting that this issue has been reported and triaged as a Moodle core issue, so go to https://tracker.moodle.org/browse/MDL-77037 for further updates on it (and vote for the issue if you are interested on it).
