### ISSUE TITLE
Exception: Return value must be of type string, null returned

### ISSUE THREAD

**Issue by pefo5543** [iarenaza/moodle-filter_multilang2#45]
We get an exception in filter_multilang2 commit eb53872169389f3b80623b6e05277e45dc0b4579 
in Moodle 3.4, with php 8.1, when filter function return null.

Perhaps you can update @return string to @return string|null ?

![multilang2](https://github.com/iarenaza/moodle-filter_multilang2/assets/17831189/62a06377-218f-450e-9fcc-bf2c078c7983)

**Comment by lucaboesch** [comment]
Moodle 3.4?

**Comment by pefo5543** [comment]
Yes

**Comment by KepaUrzelai** [comment]
Hello @pefo5543 ,

I'm sorry but [support for Moodle 3.4](https://moodledev.io/general/releases#moodle-34) has ended officialy. As long as the [support for filter_multilang2 ](https://moodle.org/plugins/filter_multilang2/versions) plugin version 1.1.1 (the one compatible with Moodle 3.4). I highly recommend updating your Moodle instance and using our last plugin version 2.0.0.

Best regards,

Kepa

**Comment by iarenaza** [comment]
Hummm, even if support for Moodle 3.4 has ended, and the plugin version @pefo5543 is using is not the latest one, s/he has a point. When I added return types to the functions, I didn't notice that the `filter` function can be called (wrongly!) with non-string values to filter. That includes not just `null` (like in this case), but also numbers and other kind of more complex values (arrays, etc).

I say "wrongly" because the multilang2 filter is only supposed to be called when `format_string` or `format_text` functions are used. And the names of those functions clearly hints at what they are supposed to be dealing with (strings). 

But as can be seen here, code out there calls them with `null` values (and other things) that don't make sense in this context. That is why these [lines are at the very top](https://github.com/iarenaza/moodle-filter_multilang2/blob/master/filter.php#L138-L141) of the `filter` function. Anything that can't be filtered is simply returned as-is.

Which is where my mistake comes into play. In those cases we don't return a string. We return something else (a `null`,  a number, an array, you name it). So clearly the return type of the `filter` function shouldn't be `string`, but "anything". Thus, we need to remove the return type from the definition.

I will take care of it, and add some unit tests to make sure we don't reintroduce this again down the road :smiley:

**Comment by iarenaza** [comment]
While locally running the new unit tests I added (before committing and pushing), I've found that the "filter_strage_pre_XXXX" functions that were added in MDL-77525 have the same type restrictions in place. They enforce the first parameter to be a `string`, and the return type to be a `string` too. So even if the `filter` function is more liberal, those "filter_stage_pre_XXX" functions will throw a TypeError too, if they are fed with anything that is not a `string`.

That means that, from Moodle 3.9.23, 3.11.16, 4.0.10, 4.1.5 and 4.2.2 onward (the versions where MDL-77525 was applied), the filtering operation will throw a TypeError even if our `filter` function removes the return type restriction. And we cannot remove the types restrictions for the "filter_strage_pre_XXXX" functions in our filter code, because their signature definition must match those of the `moodle_text_filter` base class.

Thus I assume no Moodle core code ever calls a text filter with anything that is not a string. Otherwise the calling code would get a TypeError exception. Which means those calls could only come from third party plugins that are not doing the right thing, and they should be fixed.

For this reasoning, the proposed solution will be applied to the latest plugin version only, plus **exceptionally** to the 1.1.2 version. To cover a few more Moodle versions that are -unfortunately- still being used (2.0.x only supports Moodle 3.11 onward, but e.g., Moodle 3.9.x was discontinued just two months ago)

If you are running a Moodle version older than those stated above, the "filter_strage_pre_XXXX" functions will not exist in the base class, and won't be called. Thus, no TypeError exceptions will be thrown. And the `filter` function, once the fix is applied, shouldn't throw a TypeError exception either.

**Comment by iarenaza** [comment]
Upon further analysis, no changes are needed for 1.1.2 version of the plugin. That version doesn't have any type hints at all, and doesn't implement any of the "filter_strage_pre_XXXX" functions. But it is not supposed to, as the 1.1.2 version predates MDL-77525. This is not a problem if used with Moodle versions that already include MDL-77525, as the default implementation in the base class `moodle_text_filter` class for those functions is to return the `text` argument verbatim.

Thus, no changes will be done in plugin version 1.1.2 (or earlier), and the fix will be applied to version 2.0.0 only. 

Note that version 2.0.0 only supports Moodle 3.11 or later. You cannot install and use it in earlier versions unless you change the `version.php` file of the filter. If you are already doing this change to use it with Moodle 3.4, you can as well change the `filter.php` file and remote the type constraints from the functions (both from the arguments and the return value).

In any case, the fix will be more cosmetic than anything. Even with the fix applied, any Moodle version supported by the plugin that has already applies MDL-77525 will throw an TypeError exceptionsthe moment a `null` (or any non-string value) is passed as an argument (for the reasons stated previously in this issue, about the  "filter_strage_pre_XXXX" functions signature).
