### ISSUE TITLE
Using multilang in choice answer quiz

### ISSUE THREAD

**Issue by darioroig** [iarenaza/moodle-filter_multilang2#9]
Hello!
In Moodle 3.3.1 and multi-lang Contect (v2) 1.0.5.
Steps:
One. create a new question with multilang text in the answer option.
Two. edit the question, and now in the question text and in the other options, you can see the value of option 3
Here you can see some screenshots 
http://www.uv.es/dario/quiz/quizQuestion.png.
Grettings

**Comment by iarenaza** [comment]
Hello Dario,

I'm probably doing something wrong or missing something, but I can't reproduce the problem. As the screenshot you attach doesn't show the whole question editing screen, I'm not sure what to look for.

On the other hand, I see you are using one of the editor plugins to highlight multilang tags. May I ask you which one? Just to make sure that the problem is not produced by editor plugin.

I suspect the problem you are seeing is not related to the multilang2 filter plugin, as the plugin is not called at all when the text is being edited. It is only called when the text is being displayed as part of Moodle "content presentation".

Saludos.
Iñaki.

**Comment by darioroig** [comment]
Hi Iñaki!  We have installed atto_multilang2. We have disabled the option Highlight delimiters and the bug was solved. I'm going to report in the right place.

Atto: Multi-Language Content
https://moodle.org/plugins/pluginversion.php?id=14080

Thanks for the help.
